### ISSUE TITLE
Comparison section contains "not as a comparison"

### ISSUE THREAD

**Issue by rhagenson** [ponylang/ponylang-website#585]
The comparison section added in #580 which then caused #579 to move location now contains the phrase "This info is provided as a mental model, and not as a comparison." which, given it is now in a section explicitly for comparisons is confusing. 

I believe the intent of the above phrase is to say that an empty Pony actor being 240 bytes whereas "a Goroutine is 2KB, a BEAM process is 1.2KB, and an OS thread is >1MB" is not meant to suggest Pony is even lighter (and assumed faster) and is so how superior to the other approaches.

@thomastay Am I misinterpreting you here?

**Comment by thomastay** [comment]
Whoops, I forgot that line was there! 
hmm, but since this issue is open, I'd like to take this issue to discuss the wording of this phrase, since I was never really that sure about it. Basically, I don't want to have any phrasing that implies Pony is better than other languages solely on actor overhead, since I think those 2KB / 1.2KB numbers include a pre-allocated heap space, whereas the 240 bytes doesn't include any preallocated space. That said, I'm relatively new to Pony so I'm not familiar with the ins and outs of the runtime. 

I.e. Pony is not necessarily lighter just by virtue of these numbers, as a lot of memory efficiency depends also on the overhead of other GC-ed objects that get stored in the heap, preallocated heap space, etc.

**Comment by rhagenson** [comment]
@thomastay No worries about the wording of the phrase! It is much easier to fix something once it is written then to get it perfect the first time.

I am also less familiar with the runtime than I probably should be for its intricacies. I see two ways to approach a rephrasing here: 1) dig into the numbers more, 2) leave the numbers out and use relative values based on an empty goroutine, process, thread, and actor. To guard against a "this is just Pony marketing" feel to it I would say something like "just as in all languages, efficiency is determined by more than just a handful of numbers" Comparing languages is really difficult because it can so often feel like a lose-lose situation where implying anything is seen as an insult to the community which uses a particular language. Perhaps ending the section by stating the relative advantages of the languages themselves might help prevent that implication of insult? "Erlang/Elixir is still one of the best choices for distributed computation, an area that has yet to mature in Pony; meanwhile, Go is a language designed with simplicity in concurrency at its forefront, simplicity is placed below other concerns in the Pony philosophy (https://www.ponylang.io/discover/#the-pony-philosophy)"? Mention relative strengths while admitting Pony's weaknesses and it should read as more welcoming.

(I apologize about getting back to you so much later -- I am a bit of an oddity in the Pony community in that I am a Bioinformatician, and through that I semi-recently switched jobs to work on COVID-19 so please excuse me losing track of time.)

**Comment by SeanTAllen** [comment]
I would go with general.

It's more likely to stay correct and less open to "well actually".

**Comment by rhagenson** [comment]
@SeanTAllen Can you clarify what you mean by "go with general"?

@thomastay Once we have the approach/wording on this refined, do you want to submit the PR, or would you like me to handle it?

**Comment by SeanTAllen** [comment]
As in, don't use exact numbers. Approximate.

**Comment by rhagenson** [comment]
Understood. Thank you.

**Comment by thomastay** [comment]
Ryan, you can go ahead with a PR if you want to, thanks
